language: node_js

node_js:
  - 0.10

before_install:
  - npm install -g gulp
  - curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip

before_script:
  - webdriver-manager update --standalone
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Immune to logouts, but not VM deprovisions!
  - nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
  - sleep 5 # wait for selenium server to actually come up

script:
  - nohup bash -c "node test/server.js 2>&1 &"
  - gulp ci